### ISSUE TITLE
`StdError` is not implemented for `CacheLoadingError`

### ISSUE THREAD

**Issue by Dessix** [ZeroTwo-Bot/cache-loader-async-rs#3]
Consider using [`thiserror`](https://docs.rs/crate/thiserror/) or similar to support usage of generic rust error-handling libraries.

**Comment by Dessix** [comment]
Additionally, it would be a nice benefit to allow generic parameterization of errors, such that an error in cache loading can be passed back to the caller with a known type.

**Comment by ByteAlex** [comment]
Hello @Dessix,
sorry I haven't seen your issue yet. I've started an implementation which handles errors in the loader. I'll see if it makes sense to extend it by a generic error parameter!

**Comment by ByteAlex** [comment]
Your suggestion made me clean up a lot of the error handling and I implemented a solution in #5, would you please check if that fits your requirements? :)

**Comment by Dessix** [comment]
It looks like it does all of what I wanted.
Potentially, a few helpers for the `CacheLoadingError` type may be warranted, such as `into_loading_error() -> Option<E>` / `as_loading_error() -> Option<&E>` helpers.

**Comment by ByteAlex** [comment]
Glad to hear that it solves the points you were missing!
Thank you for your feedback!
